// Auto-generated from images/manifest.json. Edit there and regenerate.
window.HEALTH_DATA = {
    "patient":  {
                    "name":  "Lei (Clark) Zhu",
                    "dob":  "1992-06-23",
                    "gender":  "Male"
                },
    "diagnosis":  "Right Posner-Schlossman Syndrome",
    "records":  [
                    {
                        "date":  "2019-09-06",
                        "place":  "Melbourne Pathology",
                        "category":  "Blood Test",
                        "test":  "Anti-Nuclear Antibodies (ANA)",
                        "eye":  null,
                        "result":  "Not detected",
                        "notes":  "Autoimmune screen. ANA not detected.",
                        "full":  "images/2019-09-06_MelbournePathology_Blood-ANA.jpg",
                        "thumb":  "images/thumbs/2019-09-06_MelbournePathology_Blood-ANA.jpg",
                        "w":  2268,
                        "h":  4032
                    },
                    {
                        "date":  "2019-09-06",
                        "place":  "Melbourne Pathology",
                        "category":  "Blood Test",
                        "test":  "Extractable Nuclear Antigens (ENA)",
                        "eye":  null,
                        "result":  "Negative",
                        "notes":  "Autoimmune screen. ENA negative.",
                        "full":  "images/2019-09-06_MelbournePathology_Blood-ENA.jpg",
                        "thumb":  "images/thumbs/2019-09-06_MelbournePathology_Blood-ENA.jpg",
                        "w":  2268,
                        "h":  4032
                    },
                    {
                        "date":  "2019-09-06",
                        "place":  "Melbourne Pathology",
                        "category":  "Blood Test",
                        "test":  "Full Blood Examination (Haematology)",
                        "eye":  null,
                        "result":  "Within normal limits",
                        "notes":  "Haemoglobin 164, WCC 7.5, Platelets 303 â€” all normal.",
                        "full":  "images/2019-09-06_MelbournePathology_Blood-FBE-Haematology.jpg",
                        "thumb":  "images/thumbs/2019-09-06_MelbournePathology_Blood-FBE-Haematology.jpg",
                        "w":  2268,
                        "h":  4032
                    },
                    {
                        "date":  "2019-09-06",
                        "place":  "Melbourne Pathology",
                        "category":  "Blood Test",
                        "test":  "Diabetes (HbA1c)",
                        "eye":  null,
                        "result":  "HbA1c 4.9% (normal)",
                        "notes":  "No evidence of diabetes.",
                        "full":  "images/2019-09-06_MelbournePathology_Blood-HbA1c.jpg",
                        "thumb":  "images/thumbs/2019-09-06_MelbournePathology_Blood-HbA1c.jpg",
                        "w":  2268,
                        "h":  4032
                    },
                    {
                        "date":  "2019-09-06",
                        "place":  "Melbourne Pathology",
                        "category":  "Blood Test",
                        "test":  "Biochemistry (EUC / LFT)",
                        "eye":  null,
                        "result":  "Within normal limits",
                        "notes":  "Electrolytes, renal and liver function normal. eGFR \u003e 90, no evidence of kidney disease.",
                        "full":  "images/2019-09-06_MelbournePathology_Blood-Biochemistry-EUC-LFT.jpg",
                        "thumb":  "images/thumbs/2019-09-06_MelbournePathology_Blood-Biochemistry-EUC-LFT.jpg",
                        "w":  2268,
                        "h":  4032
                    },
                    {
                        "date":  "2020-10-20",
                        "place":  "Specsavers Melbourne Central",
                        "category":  "Visual Field",
                        "test":  "Humphrey 24-2 Threshold (SITA Fast)",
                        "eye":  "OD",
                        "result":  "VFI 78%, GHT Outside Normal Limits, MD -11.27 dB",
                        "notes":  "Right eye field defect â€” consistent with glaucomatous damage.",
                        "full":  "images/2020-10-20_Specsavers_VisualField-24-2_OD.jpg",
                        "thumb":  "images/thumbs/2020-10-20_Specsavers_VisualField-24-2_OD.jpg",
                        "w":  3213,
                        "h":  5712
                    },
                    {
                        "date":  "2020-10-20",
                        "place":  "Specsavers Melbourne Central",
                        "category":  "Visual Field",
                        "test":  "Humphrey 24-2 Threshold (SITA Fast)",
                        "eye":  "OS",
                        "result":  "VFI 100%, GHT Within Normal Limits, MD -0.05 dB (low reliability)",
                        "notes":  "Left eye field normal.",
                        "full":  "images/2020-10-20_Specsavers_VisualField-24-2_OS.jpg",
                        "thumb":  "images/thumbs/2020-10-20_Specsavers_VisualField-24-2_OS.jpg",
                        "w":  3213,
                        "h":  5712
                    },
                    {
                        "date":  "2023-02-23",
                        "place":  "Eye Surgery Associates",
                        "category":  "Specialist Letter",
                        "test":  "Consultation letter (A/Prof Simon Skalicky)",
                        "eye":  "OD",
                        "result":  "Diagnosis: Right Posner-Schlossman syndrome",
                        "notes":  "Page 1/2. VA R 6/6 L 6/6; IOP R 12 L 15; Pachymetry R 555um L 577um. Right RAPD, right cupped disc C/D 0.8, left C/D 0.4. Treatment: Cosopt bd RE, wean Pred Forte.",
                        "full":  "images/2023-02-23_EyeSurgeryAssociates_ConsultLetter-PosnerSchlossman_p1.jpg",
                        "thumb":  "images/thumbs/2023-02-23_EyeSurgeryAssociates_ConsultLetter-PosnerSchlossman_p1.jpg",
                        "w":  3072,
                        "h":  4096
                    },
                    {
                        "date":  "2023-02-23",
                        "place":  "Eye Surgery Associates",
                        "category":  "Specialist Letter",
                        "test":  "Consultation letter (A/Prof Simon Skalicky)",
                        "eye":  null,
                        "result":  "Follow up 4-5 weeks",
                        "notes":  "Page 2/2. Signed by A/Prof Simon Skalicky, Glaucoma \u0026 Cataract Specialist.",
                        "full":  "images/2023-02-23_EyeSurgeryAssociates_ConsultLetter-PosnerSchlossman_p2.jpg",
                        "thumb":  "images/thumbs/2023-02-23_EyeSurgeryAssociates_ConsultLetter-PosnerSchlossman_p2.jpg",
                        "w":  3072,
                        "h":  4096
                    },
                    {
                        "date":  "2023-02-23",
                        "place":  "Eye Surgery Associates",
                        "category":  "Visual Field",
                        "test":  "Humphrey 24-2 Threshold (SITA Standard)",
                        "eye":  "OS",
                        "result":  "VFI 99%, GHT Borderline, MD -0.83 dB",
                        "notes":  "Left eye field essentially normal.",
                        "full":  "images/2023-02-23_EyeSurgeryAssociates_VisualField-24-2_OS.jpg",
                        "thumb":  "images/thumbs/2023-02-23_EyeSurgeryAssociates_VisualField-24-2_OS.jpg",
                        "w":  3072,
                        "h":  4096
                    },
                    {
                        "date":  "2023-02-23",
                        "place":  "Eye Surgery Associates",
                        "category":  "Visual Field",
                        "test":  "Humphrey 24-2 Threshold (SITA Standard)",
                        "eye":  "OD",
                        "result":  "VFI 63%, GHT Outside Normal Limits, MD -14.36 dB",
                        "notes":  "Right eye field defect â€” progression vs 2020.",
                        "full":  "images/2023-02-23_EyeSurgeryAssociates_VisualField-24-2_OD.jpg",
                        "thumb":  "images/thumbs/2023-02-23_EyeSurgeryAssociates_VisualField-24-2_OD.jpg",
                        "w":  3024,
                        "h":  4032
                    },
                    {
                        "date":  "2023-02-23",
                        "place":  "Eye Surgery Associates",
                        "category":  "OCT",
                        "test":  "Ganglion Cell (GCL) Analysis â€” Macular Cube 512x128",
                        "eye":  "OU",
                        "result":  "OD reduced GCL thickness (red sectors); OS normal (green)",
                        "notes":  "Ganglion cell loss in right eye.",
                        "full":  "images/2023-02-23_EyeSurgeryAssociates_OCT-GanglionCell_OU.jpg",
                        "thumb":  "images/thumbs/2023-02-23_EyeSurgeryAssociates_OCT-GanglionCell_OU.jpg",
                        "w":  3024,
                        "h":  4032
                    },
                    {
                        "date":  "2023-02-23",
                        "place":  "Eye Surgery Associates",
                        "category":  "OCT",
                        "test":  "HD 5 Line Raster",
                        "eye":  "OD",
                        "result":  null,
                        "notes":  "Right eye high-definition raster B-scan.",
                        "full":  "images/2023-02-23_EyeSurgeryAssociates_OCT-HD5LineRaster_OD.jpg",
                        "thumb":  "images/thumbs/2023-02-23_EyeSurgeryAssociates_OCT-HD5LineRaster_OD.jpg",
                        "w":  3024,
                        "h":  4032
                    },
                    {
                        "date":  "2023-02-23",
                        "place":  "Eye Surgery Associates",
                        "category":  "OCT",
                        "test":  "HD 5 Line Raster",
                        "eye":  "OS",
                        "result":  null,
                        "notes":  "Left eye high-definition raster B-scan.",
                        "full":  "images/2023-02-23_EyeSurgeryAssociates_OCT-HD5LineRaster_OS.jpg",
                        "thumb":  "images/thumbs/2023-02-23_EyeSurgeryAssociates_OCT-HD5LineRaster_OS.jpg",
                        "w":  3024,
                        "h":  4032
                    },
                    {
                        "date":  "2023-02-23",
                        "place":  "Eye Surgery Associates",
                        "category":  "OCT",
                        "test":  "Macula Thickness â€” Macular Cube 512x128",
                        "eye":  "OU",
                        "result":  null,
                        "notes":  "Macular thickness map, both eyes.",
                        "full":  "images/2023-02-23_EyeSurgeryAssociates_OCT-MaculaThickness_OU.jpg",
                        "thumb":  "images/thumbs/2023-02-23_EyeSurgeryAssociates_OCT-MaculaThickness_OU.jpg",
                        "w":  3024,
                        "h":  4032
                    },
                    {
                        "date":  "2023-02-23",
                        "place":  "Eye Surgery Associates",
                        "category":  "OCT",
                        "test":  "ONH \u0026 RNFL Analysis â€” Optic Disc Cube 200x200",
                        "eye":  "OU",
                        "result":  null,
                        "notes":  "Optic nerve head and RNFL, both eyes.",
                        "full":  "images/2023-02-23_EyeSurgeryAssociates_OCT-OpticDiscRNFL_OU.jpg",
                        "thumb":  "images/thumbs/2023-02-23_EyeSurgeryAssociates_OCT-OpticDiscRNFL_OU.jpg",
                        "w":  3024,
                        "h":  4032
                    },
                    {
                        "date":  "2023-04-18",
                        "place":  "Beijing Tongren Hospital",
                        "category":  "Visual Field",
                        "test":  "Humphrey 24-2 Threshold (SITA Fast)",
                        "eye":  "OS",
                        "result":  "VFI 99%, within normal range, MD -0.59 dB",
                        "notes":  "Left eye field normal.",
                        "full":  "images/2023-04-18_BeijingTongrenHospital_VisualField-24-2_OS.jpg",
                        "thumb":  "images/thumbs/2023-04-18_BeijingTongrenHospital_VisualField-24-2_OS.jpg",
                        "w":  3072,
                        "h":  4096
                    },
                    {
                        "date":  "2023-04-18",
                        "place":  "Beijing Tongren Hospital",
                        "category":  "Visual Field",
                        "test":  "Humphrey 24-2 Threshold (SITA Fast)",
                        "eye":  "OD",
                        "result":  "VFI 68%, outside normal range, MD -14.38 dB",
                        "notes":  "Right eye field defect â€” stable/progressing vs Feb 2023.",
                        "full":  "images/2023-04-18_BeijingTongrenHospital_VisualField-24-2_OD.jpg",
                        "thumb":  "images/thumbs/2023-04-18_BeijingTongrenHospital_VisualField-24-2_OD.jpg",
                        "w":  3072,
                        "h":  4096
                    },
                    {
                        "date":  "2023-04-18",
                        "place":  "Beijing Tongren Hospital",
                        "category":  "OCT",
                        "test":  "ONH \u0026 RNFL Analysis â€” Optic Disc Cube 200x200",
                        "eye":  "OU",
                        "result":  "OD reduced RNFL (C/D 0.82); OS normal (C/D 0.66)",
                        "notes":  "Optic nerve head and RNFL, both eyes. Right eye thinning.",
                        "full":  "images/2023-04-18_BeijingTongrenHospital_OCT-OpticDiscRNFL_OU.jpg",
                        "thumb":  "images/thumbs/2023-04-18_BeijingTongrenHospital_OCT-OpticDiscRNFL_OU.jpg",
                        "w":  3072,
                        "h":  4096
                    },
                    {
                        "date":  "2023-04-18",
                        "place":  "Beijing Tongren Hospital",
                        "category":  "OCT",
                        "test":  "Macula Thickness â€” Macular Cube 512x128",
                        "eye":  "OU",
                        "result":  "OD reduced (red); OS normal (green)",
                        "notes":  "Macular thickness map, both eyes.",
                        "full":  "images/2023-04-18_BeijingTongrenHospital_OCT-MaculaThickness_OU.jpg",
                        "thumb":  "images/thumbs/2023-04-18_BeijingTongrenHospital_OCT-MaculaThickness_OU.jpg",
                        "w":  3072,
                        "h":  4096
                    },
                    {
                        "date":  "2023-04-18",
                        "place":  "Beijing Tongren Hospital",
                        "category":  "OCT",
                        "test":  "HD Radial",
                        "eye":  "OD",
                        "result":  null,
                        "notes":  "Right eye high-definition radial B-scan.",
                        "full":  "images/2023-04-18_BeijingTongrenHospital_OCT-HDRadial_OD.jpg",
                        "thumb":  "images/thumbs/2023-04-18_BeijingTongrenHospital_OCT-HDRadial_OD.jpg",
                        "w":  3072,
                        "h":  4096
                    },
                    {
                        "date":  "2023-04-18",
                        "place":  "Beijing Tongren Hospital",
                        "category":  "OCT",
                        "test":  "HD Radial",
                        "eye":  "OS",
                        "result":  null,
                        "notes":  "Left eye high-definition radial B-scan.",
                        "full":  "images/2023-04-18_BeijingTongrenHospital_OCT-HDRadial_OS.jpg",
                        "thumb":  "images/thumbs/2023-04-18_BeijingTongrenHospital_OCT-HDRadial_OS.jpg",
                        "w":  3072,
                        "h":  4096
                    }
                ]
};
