// Auto-generated from images/manifest.json. Edit there and regenerate.
window.HEALTH_DATA = {
 "patient": {
  "name": "Lei Zhu (Clark)",
  "dob": "1992-06-23",
  "gender": "Male"
 },
 "diagnosis": "Right Posner-Schlossman Syndrome",
 "records": [
  {
   "date": "2019-09-06",
   "place": "Melbourne Pathology",
   "category": "Blood Test",
   "test": "Anti-Nuclear Antibodies (ANA)",
   "eye": null,
   "result": "Not detected",
   "notes": "Autoimmune screen. ANA not detected.",
   "full": "images/2019-09-06_MelbournePathology_Blood-ANA.jpg",
   "thumb": "images/thumbs/2019-09-06_MelbournePathology_Blood-ANA.jpg",
   "w": 2268,
   "h": 4032
  },
  {
   "date": "2019-09-06",
   "place": "Melbourne Pathology",
   "category": "Blood Test",
   "test": "Extractable Nuclear Antigens (ENA)",
   "eye": null,
   "result": "Negative",
   "notes": "Autoimmune screen. ENA negative.",
   "full": "images/2019-09-06_MelbournePathology_Blood-ENA.jpg",
   "thumb": "images/thumbs/2019-09-06_MelbournePathology_Blood-ENA.jpg",
   "w": 2268,
   "h": 4032
  },
  {
   "date": "2019-09-06",
   "place": "Melbourne Pathology",
   "category": "Blood Test",
   "test": "Full Blood Examination (Haematology)",
   "eye": null,
   "result": "Within normal limits",
   "notes": "Haemoglobin 164, WCC 7.5, Platelets 303 — all normal.",
   "full": "images/2019-09-06_MelbournePathology_Blood-FBE-Haematology.jpg",
   "thumb": "images/thumbs/2019-09-06_MelbournePathology_Blood-FBE-Haematology.jpg",
   "w": 2268,
   "h": 4032
  },
  {
   "date": "2019-09-06",
   "place": "Melbourne Pathology",
   "category": "Blood Test",
   "test": "Diabetes (HbA1c)",
   "eye": null,
   "result": "HbA1c 4.9% (normal)",
   "notes": "No evidence of diabetes.",
   "full": "images/2019-09-06_MelbournePathology_Blood-HbA1c.jpg",
   "thumb": "images/thumbs/2019-09-06_MelbournePathology_Blood-HbA1c.jpg",
   "w": 2268,
   "h": 4032
  },
  {
   "date": "2019-09-06",
   "place": "Melbourne Pathology",
   "category": "Blood Test",
   "test": "Biochemistry (EUC / LFT)",
   "eye": null,
   "result": "Within normal limits",
   "notes": "Electrolytes, renal and liver function normal. eGFR > 90, no evidence of kidney disease.",
   "full": "images/2019-09-06_MelbournePathology_Blood-Biochemistry-EUC-LFT.jpg",
   "thumb": "images/thumbs/2019-09-06_MelbournePathology_Blood-Biochemistry-EUC-LFT.jpg",
   "w": 2268,
   "h": 4032
  },
  {
   "date": "2020-10-20",
   "place": "Specsavers Melbourne Central",
   "category": "Visual Field",
   "test": "Humphrey 24-2 Threshold (SITA Fast)",
   "eye": "OD",
   "result": "VFI 78%, GHT Outside Normal Limits, MD -11.27 dB",
   "notes": "Right eye field defect — consistent with glaucomatous damage.",
   "full": "images/2020-10-20_Specsavers_VisualField-24-2_OD.jpg",
   "thumb": "images/thumbs/2020-10-20_Specsavers_VisualField-24-2_OD.jpg",
   "w": 3213,
   "h": 5712
  },
  {
   "date": "2020-10-20",
   "place": "Specsavers Melbourne Central",
   "category": "Visual Field",
   "test": "Humphrey 24-2 Threshold (SITA Fast)",
   "eye": "OS",
   "result": "VFI 100%, GHT Within Normal Limits, MD -0.05 dB (low reliability)",
   "notes": "Left eye field normal.",
   "full": "images/2020-10-20_Specsavers_VisualField-24-2_OS.jpg",
   "thumb": "images/thumbs/2020-10-20_Specsavers_VisualField-24-2_OS.jpg",
   "w": 3213,
   "h": 5712
  },
  {
   "date": "2023-02-23",
   "place": "Eye Surgery Associates",
   "category": "Visual Field",
   "test": "Humphrey 24-2 Threshold (SITA Standard)",
   "eye": "OS",
   "result": "VFI 99%, GHT Borderline, MD -0.83 dB",
   "notes": "Left eye field essentially normal.",
   "full": "images/2023-02-23_EyeSurgeryAssociates_VisualField-24-2_OS.jpg",
   "thumb": "images/thumbs/2023-02-23_EyeSurgeryAssociates_VisualField-24-2_OS.jpg",
   "w": 3072,
   "h": 4096
  },
  {
   "date": "2023-02-23",
   "place": "Eye Surgery Associates",
   "category": "Visual Field",
   "test": "Humphrey 24-2 Threshold (SITA Standard)",
   "eye": "OD",
   "result": "VFI 63%, GHT Outside Normal Limits, MD -14.36 dB",
   "notes": "Right eye field defect — progression vs 2020.",
   "full": "images/2023-02-23_EyeSurgeryAssociates_VisualField-24-2_OD.jpg",
   "thumb": "images/thumbs/2023-02-23_EyeSurgeryAssociates_VisualField-24-2_OD.jpg",
   "w": 3024,
   "h": 4032
  },
  {
   "date": "2023-02-23",
   "place": "Eye Surgery Associates",
   "category": "OCT",
   "test": "Ganglion Cell (GCL) Analysis — Macular Cube 512x128",
   "eye": "OU",
   "result": "OD reduced GCL thickness (red sectors); OS normal (green)",
   "notes": "Ganglion cell loss in right eye.",
   "full": "images/2023-02-23_EyeSurgeryAssociates_OCT-GanglionCell_OU.jpg",
   "thumb": "images/thumbs/2023-02-23_EyeSurgeryAssociates_OCT-GanglionCell_OU.jpg",
   "w": 3024,
   "h": 4032
  },
  {
   "date": "2023-02-23",
   "place": "Eye Surgery Associates",
   "category": "OCT",
   "test": "HD 5 Line Raster",
   "eye": "OD",
   "result": null,
   "notes": "Right eye high-definition raster B-scan.",
   "full": "images/2023-02-23_EyeSurgeryAssociates_OCT-HD5LineRaster_OD.jpg",
   "thumb": "images/thumbs/2023-02-23_EyeSurgeryAssociates_OCT-HD5LineRaster_OD.jpg",
   "w": 3024,
   "h": 4032
  },
  {
   "date": "2023-02-23",
   "place": "Eye Surgery Associates",
   "category": "OCT",
   "test": "HD 5 Line Raster",
   "eye": "OS",
   "result": null,
   "notes": "Left eye high-definition raster B-scan.",
   "full": "images/2023-02-23_EyeSurgeryAssociates_OCT-HD5LineRaster_OS.jpg",
   "thumb": "images/thumbs/2023-02-23_EyeSurgeryAssociates_OCT-HD5LineRaster_OS.jpg",
   "w": 3024,
   "h": 4032
  },
  {
   "date": "2023-02-23",
   "place": "Eye Surgery Associates",
   "category": "OCT",
   "test": "Macula Thickness — Macular Cube 512x128",
   "eye": "OU",
   "result": null,
   "notes": "Macular thickness map, both eyes.",
   "full": "images/2023-02-23_EyeSurgeryAssociates_OCT-MaculaThickness_OU.jpg",
   "thumb": "images/thumbs/2023-02-23_EyeSurgeryAssociates_OCT-MaculaThickness_OU.jpg",
   "w": 3024,
   "h": 4032
  },
  {
   "date": "2023-02-23",
   "place": "Eye Surgery Associates",
   "category": "OCT",
   "test": "ONH & RNFL Analysis — Optic Disc Cube 200x200",
   "eye": "OU",
   "result": null,
   "notes": "Optic nerve head and RNFL, both eyes.",
   "full": "images/2023-02-23_EyeSurgeryAssociates_OCT-OpticDiscRNFL_OU.jpg",
   "thumb": "images/thumbs/2023-02-23_EyeSurgeryAssociates_OCT-OpticDiscRNFL_OU.jpg",
   "w": 3024,
   "h": 4032
  },
  {
   "date": "2023-04-18",
   "place": "Beijing Tongren Hospital",
   "category": "Visual Field",
   "test": "Humphrey 24-2 Threshold (SITA Fast)",
   "eye": "OS",
   "result": "VFI 99%, within normal range, MD -0.59 dB",
   "notes": "Left eye field normal.",
   "full": "images/2023-04-18_BeijingTongrenHospital_VisualField-24-2_OS.jpg",
   "thumb": "images/thumbs/2023-04-18_BeijingTongrenHospital_VisualField-24-2_OS.jpg",
   "w": 3072,
   "h": 4096
  },
  {
   "date": "2023-04-18",
   "place": "Beijing Tongren Hospital",
   "category": "Visual Field",
   "test": "Humphrey 24-2 Threshold (SITA Fast)",
   "eye": "OD",
   "result": "VFI 68%, outside normal range, MD -14.38 dB",
   "notes": "Right eye field defect — stable/progressing vs Feb 2023.",
   "full": "images/2023-04-18_BeijingTongrenHospital_VisualField-24-2_OD.jpg",
   "thumb": "images/thumbs/2023-04-18_BeijingTongrenHospital_VisualField-24-2_OD.jpg",
   "w": 3072,
   "h": 4096
  },
  {
   "date": "2023-04-18",
   "place": "Beijing Tongren Hospital",
   "category": "OCT",
   "test": "ONH & RNFL Analysis — Optic Disc Cube 200x200",
   "eye": "OU",
   "result": "OD reduced RNFL (C/D 0.82); OS normal (C/D 0.66)",
   "notes": "Optic nerve head and RNFL, both eyes. Right eye thinning.",
   "full": "images/2023-04-18_BeijingTongrenHospital_OCT-OpticDiscRNFL_OU.jpg",
   "thumb": "images/thumbs/2023-04-18_BeijingTongrenHospital_OCT-OpticDiscRNFL_OU.jpg",
   "w": 3072,
   "h": 4096
  },
  {
   "date": "2023-04-18",
   "place": "Beijing Tongren Hospital",
   "category": "OCT",
   "test": "Macula Thickness — Macular Cube 512x128",
   "eye": "OU",
   "result": "OD reduced (red); OS normal (green)",
   "notes": "Macular thickness map, both eyes.",
   "full": "images/2023-04-18_BeijingTongrenHospital_OCT-MaculaThickness_OU.jpg",
   "thumb": "images/thumbs/2023-04-18_BeijingTongrenHospital_OCT-MaculaThickness_OU.jpg",
   "w": 3072,
   "h": 4096
  },
  {
   "date": "2023-04-18",
   "place": "Beijing Tongren Hospital",
   "category": "OCT",
   "test": "HD Radial",
   "eye": "OD",
   "result": null,
   "notes": "Right eye high-definition radial B-scan.",
   "full": "images/2023-04-18_BeijingTongrenHospital_OCT-HDRadial_OD.jpg",
   "thumb": "images/thumbs/2023-04-18_BeijingTongrenHospital_OCT-HDRadial_OD.jpg",
   "w": 3072,
   "h": 4096
  },
  {
   "date": "2023-04-18",
   "place": "Beijing Tongren Hospital",
   "category": "OCT",
   "test": "HD Radial",
   "eye": "OS",
   "result": null,
   "notes": "Left eye high-definition radial B-scan.",
   "full": "images/2023-04-18_BeijingTongrenHospital_OCT-HDRadial_OS.jpg",
   "thumb": "images/thumbs/2023-04-18_BeijingTongrenHospital_OCT-HDRadial_OS.jpg",
   "w": 3072,
   "h": 4096
  },
  {
   "date": "2026-04-01",
   "place": "Southwest Hospital, Chongqing",
   "category": "Summary",
   "test": "Annual check-up summary",
   "eye": null,
   "result": "4 findings: hyperlipidaemia, overweight, severe hepatic steatosis, elevated ALT/AST",
   "notes": "Overall summary of the 2026 annual health check-up with the four flagged findings and lifestyle advice.",
   "full": "images/2026-04-01_SouthwestHospital_Summary.png",
   "thumb": "images/thumbs/2026-04-01_SouthwestHospital_Summary.png",
   "w": 1240,
   "h": 1754,
   "pdf": "images/2026-04-01_SouthwestHospital_Summary.pdf"
  },
  {
   "date": "2026-04-01",
   "place": "Southwest Hospital, Chongqing",
   "category": "Blood Test",
   "test": "Full blood panel",
   "eye": null,
   "result": "ALT 85.6 H, AST 53.9 H, TG 1.83 H, HCT 50.3 H; tumour markers, HbA1c, coagulation all normal",
   "notes": "All blood panels from the check-up. Flagged: ALT, AST (liver enzymes), triglycerides, haematocrit, monocytes. Tumour markers, glucose/HbA1c, kidney function and coagulation normal.",
   "full": "images/2026-04-01_SouthwestHospital_Blood-Tests.png",
   "thumb": "images/thumbs/2026-04-01_SouthwestHospital_Blood-Tests.png",
   "w": 1240,
   "h": 5262,
   "pdf": "images/2026-04-01_SouthwestHospital_Blood-Tests.pdf"
  },
  {
   "date": "2026-04-01",
   "place": "Southwest Hospital, Chongqing",
   "category": "Urinalysis",
   "test": "Urine routine + microalbumin",
   "eye": null,
   "result": "All parameters normal / negative",
   "notes": "Complete urinalysis including microalbumin. All values within normal limits / negative.",
   "full": "images/2026-04-01_SouthwestHospital_Urinalysis.png",
   "thumb": "images/thumbs/2026-04-01_SouthwestHospital_Urinalysis.png",
   "w": 1240,
   "h": 1754,
   "pdf": "images/2026-04-01_SouthwestHospital_Urinalysis.pdf"
  },
  {
   "date": "2026-04-01",
   "place": "Southwest Hospital, Chongqing",
   "category": "Physical Exam",
   "test": "Vital signs & anthropometry",
   "eye": null,
   "result": "BP 117/68, pulse 84; BMI 25.5 (overweight)",
   "notes": "Vital signs and body measurements. Blood pressure and pulse normal; BMI 25.5 (overweight).",
   "full": "images/2026-04-01_SouthwestHospital_Physical-Exam.png",
   "thumb": "images/thumbs/2026-04-01_SouthwestHospital_Physical-Exam.png",
   "w": 1240,
   "h": 1754,
   "pdf": "images/2026-04-01_SouthwestHospital_Physical-Exam.pdf"
  },
  {
   "date": "2026-04-01",
   "place": "Southwest Hospital, Chongqing",
   "category": "ECG",
   "test": "12-lead ECG",
   "eye": null,
   "result": "Sinus arrhythmia (normal variant); rate 78 bpm, intervals normal",
   "notes": "12-lead ECG. Diagnosis: sinus arrhythmia (a normal rhythm variant). All intervals and axis within normal limits. Original trace included.",
   "full": "images/2026-04-01_SouthwestHospital_ECG.png",
   "thumb": "images/thumbs/2026-04-01_SouthwestHospital_ECG.png",
   "w": 1406,
   "h": 3743,
   "pdf": "images/2026-04-01_SouthwestHospital_ECG.pdf"
  },
  {
   "date": "2026-04-01",
   "place": "Southwest Hospital, Chongqing",
   "category": "Chest X-ray",
   "test": "PA chest radiograph",
   "eye": null,
   "result": "No abnormality",
   "notes": "Posterior-anterior chest radiograph reported as normal.",
   "full": "images/2026-04-01_SouthwestHospital_Chest-Xray.png",
   "thumb": "images/thumbs/2026-04-01_SouthwestHospital_Chest-Xray.png",
   "w": 1240,
   "h": 1754,
   "pdf": "images/2026-04-01_SouthwestHospital_Chest-Xray.pdf"
  },
  {
   "date": "2026-04-01",
   "place": "Southwest Hospital, Chongqing",
   "category": "Ultrasound",
   "test": "Liver/GB/pancreas/spleen/kidneys + portal vein",
   "eye": null,
   "result": "Liver, gallbladder, pancreas, spleen, both kidneys — no significant abnormality",
   "notes": "Colour Doppler ultrasound of liver, gallbladder, pancreas, spleen, both kidneys and portal vein. No significant abnormality.",
   "full": "images/2026-04-01_SouthwestHospital_Abdominal-Ultrasound.png",
   "thumb": "images/thumbs/2026-04-01_SouthwestHospital_Abdominal-Ultrasound.png",
   "w": 1240,
   "h": 1754,
   "pdf": "images/2026-04-01_SouthwestHospital_Abdominal-Ultrasound.pdf"
  },
  {
   "date": "2026-04-01",
   "place": "Southwest Hospital, Chongqing",
   "category": "Pulmonary Function",
   "test": "Spirometry",
   "eye": null,
   "result": "Normal ventilatory function",
   "notes": "Spirometry. FVC, FEV1 and FEV1/FVC all normal — normal ventilatory function.",
   "full": "images/2026-04-01_SouthwestHospital_Pulmonary-Function.png",
   "thumb": "images/thumbs/2026-04-01_SouthwestHospital_Pulmonary-Function.png",
   "w": 1240,
   "h": 1754,
   "pdf": "images/2026-04-01_SouthwestHospital_Pulmonary-Function.pdf"
  },
  {
   "date": "2026-04-01",
   "place": "Southwest Hospital, Chongqing",
   "category": "Transcranial Doppler",
   "test": "Cerebral blood flow",
   "eye": null,
   "result": "No significant abnormality",
   "notes": "Transcranial Doppler of cerebral arteries. Normal pulsatility and flow velocities; no significant abnormality. Original waveforms included.",
   "full": "images/2026-04-01_SouthwestHospital_Transcranial-Doppler.png",
   "thumb": "images/thumbs/2026-04-01_SouthwestHospital_Transcranial-Doppler.png",
   "w": 1405,
   "h": 3743,
   "pdf": "images/2026-04-01_SouthwestHospital_Transcranial-Doppler.pdf"
  },
  {
   "date": "2026-04-01",
   "place": "Southwest Hospital, Chongqing",
   "category": "Liver FibroScan",
   "test": "CAP + stiffness (E)",
   "eye": null,
   "result": "CAP 311 dB/m — severe steatosis; E 5.2 kPa — no fibrosis",
   "notes": "Transient elastography. CAP 311 dB/m indicates severe fatty liver; liver stiffness E 5.2 kPa is normal (no significant fibrosis).",
   "full": "images/2026-04-01_SouthwestHospital_Liver-FibroScan.png",
   "thumb": "images/thumbs/2026-04-01_SouthwestHospital_Liver-FibroScan.png",
   "w": 1406,
   "h": 3742,
   "pdf": "images/2026-04-01_SouthwestHospital_Liver-FibroScan.pdf"
  }
 ]
};